
export const subjects = [
  "Linear Algebra",
  "Introduction to Communication and Ethics",
  "Books, Club and Social Emotional Intelligence 1",
  "Programming Methodology in Python",
  "Introduction to Computers",
  "CS 106 Python Project Course",
  "Calculus",
  "Mathematical Foundations of Computing",
  "Communication and Ethics",
  "Books, Club and Social Emotional Intelligence 2",
  "Data Handling in Python",
  "Data Structures and Algorithms",
  "Probability for Computer Science",
  "Communication and Book Club",
  "Object Oriented Programming",
  "Advanced Data Structures and Algorithms",
  "Database Management Systems",
  "Artificial Intelligence",
  "CoCo Summer",
  "Advanced Object Oriented Programming",
  "Search Engines and Information Retrieval",
  "Mining Massive Datasets",
  "Computer Organization and Systems",
  "Machine Learning",
  "Web Applications Development",
  "Creative Problem Solving",
  "Operating Systems Principles",
  "Deep Learning",
  "Internship",
  "Software Engineering Project, Including Technical Writing",
  "Economics for Computer Science",
  "Human Computer Interaction",
  "Computer Networks",
  "Applications of Deep Learning",
  "Machine Learning Project",
];
